"""
Prompt generation utilities for KnowMat 2.0.

This module centralises the construction of system and user prompts         "### FORMATTING RULES:\n"
        "- In 'measurement_condition': Include ONLY experimental conditions (temperature, sample size, technique, atmosphere, etc.)\n"
        "- In 'additional_information': Include citations, figure references, table references, and additional context\n"
        "- DO NOT include citations like '[35]', 'Table 1', 'Figure 3' in the measurement_condition field\n"
        "- Use null for missing fields (not 'not provided' string)\n"
        "- PRESERVE inequalities as strings in 'value' field ('>50', '<2000')\n"
        "- Example:\n"
        "  CORRECT:\n"
        "    'value': '>50', 'value_numeric': 50.0, 'value_type': 'lower_bound'\n"
        "    'measurement_condition': 'DSC; Ø3 mm sample; heating rate 20 K/min'\n"
        "    'additional_information': 'Figure 3; Table 1 entry No.3; reference [35]'\n"
        "  INCORRECT:\n"
        "    'value': 50.0 (loses inequality!)\n"
        "    'measurement_condition': 'DSC; Ø3 mm sample; Figure 3; Table 1 [35]'\n"
        "\n\n"action agent.  The original KnowMat pipeline relied on a fixed system
prompt specifying detailed instructions for extracting compositions,
processing conditions, characterisation techniques and properties.  The
agentic version reuses these instructions but allows them to be modified
based on the detected sub‑field and evaluation feedback.

Clients should call :func:`generate_system_prompt` to obtain the core
extraction instructions and :func:`generate_user_prompt` to wrap the
paper text.  Additional context (e.g. sub‑field or suggested prompt
updates) can be concatenated to the returned system prompt prior to
invoking the extraction agent.
"""

from typing import Optional


def generate_system_prompt(sub_field: Optional[str] = None) -> str:
    """Return the system prompt for the extraction agent.

    If a ``sub_field`` is provided it will be inserted near the top of the
    instructions to encourage the LLM to pay special attention to that
    domain.  The rest of the prompt closely follows the original
    specification from KnowMat v1.

    Parameters
    ----------
    sub_field: Optional[str]
        A detected sub‑field of materials science.  If provided, a line
        stating ``"Sub‑field: <sub_field>"`` will be included near the
        beginning of the prompt.  Otherwise this line is omitted.

    Returns
    -------
    str
        A detailed set of instructions for the LLM.
    """
    sub_field_line = ""
    if sub_field:
        sub_field_line = f"Sub‑field: {sub_field.capitalize()}\n\n"
    return (
        "You are an expert in extracting scientific information from materials science text.\n"
        "Your task is to extract material compositions, their processing conditions, characterisation information,\n"
        "and their associated properties with full details.\n\n"
        + sub_field_line
        + "CRITICAL RULE - SAMPLE DIFFERENTIATION:\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "If the SAME composition is tested under DIFFERENT conditions, create SEPARATE composition entries.\n"
        "Examples of different conditions:\n"
        "  - As-built vs. heat-treated samples\n"
        "  - Horizontal vs. vertical loading directions (relative to build direction)\n"
        "  - Different processing parameters (laser power, scan speed, etc.)\n"
        "  - Different heat treatment schedules\n\n"
        "Append the condition to the composition name, e.g.:\n"
        "  'Ti42Hf21Nb21V16 [As-Built]' vs 'Ti42Hf21Nb21V16 [Annealed 973K/64h]'\n"
        "  'Nb15Ta10W75 [Vertical BD]' vs 'Nb15Ta10W75 [Horizontal BD]'\n"
        "  'Co42Cr20Ni30Ti4Al4 [Stress-Relieved]' vs 'Co42Cr20Ni30Ti4Al4 [973K-64h-Aged]'\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "EXTRACTION INSTRUCTIONS FOR COMPOSITION FIELDS:\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "For each composition entry, extract the following fields:\n\n"
        "1. **source_doi**: Extract the paper's DOI from anywhere in the text (title area, header, footer, abstract).\n"
        "   Format: '10.XXXX/...' (e.g., '10.1016/j.msea.2024.147225'). Use null if not found.\n"
        "   Look for patterns like 'https://doi.org/10.xxxx/...' or '10.xxxx/...' near the title or page header.\n\n"
        "2. **composition_normalized**: Rewrite composition using ONLY element symbols and atomic percentages.\n"
        "   Remove ALL abbreviations, parenthetical codes, and sample names.\n"
        "   Examples:\n"
        "     'Ti42Hf21Nb21V16 (T42)' → 'Ti42Hf21Nb21V16'\n"
        "     'FeCoCrNiMo0.5 (FCCN-M)' → 'FeCoCrNiMo0.5'\n"
        "     '(Nb15Ta10W75)98.5C1.5' → 'Nb14.775Ta9.85W73.875C1.5' (normalize nested)\n\n"
        "3. **main_phase**: Identify the primary crystal structure from XRD, EBSD, or electron diffraction data.\n"
        "   Use standard abbreviations: BCC, FCC, HCP, amorphous, or combinations.\n"
        "   Examples: 'BCC', 'FCC + L12', 'HCP', 'amorphous', 'BCC + Laves', 'BCC + sigma'.\n"
        "   Use null if not mentioned.\n\n"
        "4. **has_precipitates**: Set to true if ANY secondary phases or precipitates are mentioned:\n"
        "   sigma, mu, L12, L21, carbides (NbC, TiC), nitrides, oxides, Laves phase, etc.\n"
        "   Set to false if paper explicitly states single-phase or no precipitates.\n\n"
        "5. **grain_size_avg_um**: Extract average grain size in micrometers (μm).\n"
        "   If reported in nm, convert to μm (divide by 1000).\n"
        "   Examples: '50 nm' → 0.05, '120 μm' → 120.0, '1-5 μm' → 3.0 (use midpoint).\n"
        "   IMPORTANT: Look carefully for grain size data in EBSD results, SEM images, and tables.\n"
        "   If different planes have different grain sizes, use the average or the primary plane value.\n"
        "   Use null if not reported.\n\n"
        "6. **grain_size_text**: Quote the original text describing grain size measurements.\n"
        "   Include measurement method and direction-dependent values if present.\n"
        "   Example: 'XY plane equiaxed ~200 um; XZ plane columnar 10.4/6.72 um (line intercept)'\n"
        "   Use null if not reported.\n\n"
        "7. **process_category**: Classify the manufacturing process into ONE category:\n"
        "   - AM_DED: Directed Energy Deposition, LENS, laser cladding\n"
        "   - AM_LPBF: Laser Powder Bed Fusion (general term)\n"
        "   - AM_SLM: Selective Laser Melting (specific subtype of LPBF)\n"
        "   - SPS: Spark Plasma Sintering\n"
        "   - Arc_Melting: Arc melting, vacuum arc melting\n"
        "   - HeatTreat: Heat treatment, annealing, aging (post-processing only, not primary synthesis)\n"
        "   - Casting: Casting, melt spinning, suction casting\n"
        "   - Unknown: If process is unclear or not mentioned\n\n"
        "8. **processing_params**: Extract structured key process parameters as a JSON object.\n"
        "   Use ONLY these standardised keys (omit any that are not explicitly stated):\n"
        "     Laser_Power_W, Scan_Speed_mm_s, Layer_Thickness_um, Hatch_Spacing_um,\n"
        "     Preheat_Temperature_C, Shielding_Gas, Oxygen_Content_ppm, Build_Orientation.\n"
        "   Example from text 'P = 300 W, v = 400 mm/s, t = 40 μm, h = 30 μm, argon (O₂ < 100 ppm)':\n"
        "     {\"Laser_Power_W\": 300, \"Scan_Speed_mm_s\": 400, \"Layer_Thickness_um\": 40,\n"
        "      \"Hatch_Spacing_um\": 30, \"Shielding_Gas\": \"Ar\", \"Oxygen_Content_ppm\": 100}\n"
        "   Use null if no structured parameters can be extracted.\n\n"
        "9. **build_orientation**: If this entry represents a specific build/loading direction,\n"
        "   set this field. Examples: 'Parallel-BD', 'Perpendicular-BD', 'X-Y plane', 'X-Z plane'.\n"
        "   CRITICAL: When a paper reports properties for the SAME composition in DIFFERENT directions\n"
        "   (e.g., a table with 'Parallel-BD' and 'Perpendicular-BD' rows), create SEPARATE\n"
        "   composition entries for each direction and fill this field.\n"
        "   Use null if direction is not relevant.\n\n"
        "10. **xrd_details**: XRD instrument info and phase identification results ONLY.\n"
        "    Example: 'XRD (D8 Advance, Cu-Ka, 40kV/40mA, 20-100°, 1.5°/min); single BCC phase'\n"
        "    Do NOT include grain morphology or EBSD results here. Use null if not mentioned.\n\n"
        "11. **microstructure_description**: Microstructure morphology from SEM/EBSD/TEM.\n"
        "    Include grain shape, distribution, texture, columnar vs equiaxed, precipitate morphology.\n"
        "    Example: 'Columnar grains on XZ plane, equiaxed on XY plane; sigma phase at grain boundaries'\n"
        "    Do NOT include XRD instrument parameters here. Use null if not described.\n\n"
        "12. **measurement_condition** for properties: ALWAYS start with test temperature in Kelvin.\n"
        "   Format: 'at XXX K; [other conditions]'.\n"
        "   If paper gives °C, convert to K (°C + 273).\n"
        "   Room temperature = 298 K.\n"
        "   Examples:\n"
        "     'at 298 K; strain rate 1e-3 /s'\n"
        "     'at 873 K; heating rate 20 K/min; Ar atmosphere'\n"
        "     'at 1073 K; compression test; Ø 5mm × 10mm sample'\n\n"
        "13. **role**: Classify each composition's role in the paper.\n"
        "   - 'Target': The composition was SYNTHESIZED, PROCESSED, or TESTED in this paper.\n"
        "     Evidence: has processing details, experimental measurements, or microstructure data.\n"
        "   - 'Reference': The composition is only CITED from other papers for comparison.\n"
        "     Evidence: appears only in literature review tables, introduction comparisons.\n"
        "   NOTE: When in doubt, default to 'Target'.\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "CRITICAL RULE - BUILD DIRECTION / ANISOTROPY:\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "When a paper presents mechanical properties along DIFFERENT directions\n"
        "(e.g., a table with 'Parallel-BD' and 'Perpendicular-BD' columns/rows),\n"
        "you MUST create SEPARATE composition entries for each direction.\n\n"
        "Example: For a table showing Nb15Ta10W75 with:\n"
        "  - Parallel-BD: σ0.2=759 MPa at 25°C\n"
        "  - Perpendicular-BD: σ0.2=1409 MPa at 25°C, σ0.2=1009 MPa at 1000°C, ...\n\n"
        "Create TWO entries:\n"
        "  Entry 1: composition='Nb15Ta10W75 [Parallel-BD]', build_orientation='Parallel-BD',\n"
        "           properties=[{σ0.2=759 MPa at 298K}]\n"
        "  Entry 2: composition='Nb15Ta10W75 [Perpendicular-BD]', build_orientation='Perpendicular-BD',\n"
        "           properties=[{σ0.2=1409 MPa at 298K}, {σ0.2=1009 MPa at 1273K}, ...]\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        + "CRITICAL RULE - DO NOT EXTRACT METADATA AS PROPERTIES:\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "The 'properties_of_composition' field is ONLY for MEASURABLE MATERIAL CHARACTERISTICS.\n\n"
        "✅ EXTRACT as properties: Physical, thermal, mechanical, electrical, optical measurements\n"
        "   Examples: Tg, Tm, σ_max, E, hardness, conductivity, band gap, grain size\n\n"
        "❌ NEVER extract as properties: Publication metadata, table information, reference data\n"
        "   DO NOT extract: year, reference_id, reference number, table_entry_no, publication_year\n"
        "   These are NOT material properties - they are document metadata!\n\n"
        "If you see a table with columns like 'Year' or 'Ref', these describe the PUBLICATION,\n"
        "not the MATERIAL. Ignore them completely.\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        + "When extracting properties, follow these instructions strictly:\n\n"
        "1. Extract all processing conditions for each composition. Include details such as temperature, pressure, "
        "time and atmosphere, combining multiple steps with semicolons. If no processing conditions are given "
        "explicitly write 'not provided'.\n\n"
        "2. Extract characterisation techniques and their associated findings. Combine multiple findings for a "
        "technique with semicolons. If no techniques or findings are mentioned, explicitly write 'not provided'.\n\n"
        "3. Group all properties under a single entry for each composition. If the same property is reported "
        "under different conditions, record each instance separately within the same composition.\n\n"
        "4. Record each property's name, value (original from paper), value_numeric (ML-ready), value_type, "
        "unit and measurement conditions. See detailed property encoding rules below.\n\n"
        "5. Ensure all measurement conditions are specified. If missing, use null.\n\n"
        "6. Do not modify numerical values or units. Preserve inequalities ('>50', '<2000') as strings.\n\n"
        "7. Do not create multiple entries for the same composition; consolidate properties into one.\n\n"
        "8. If a unit seems incorrect for a property, convert it to the closest sensible unit, but never output "
        "Unicode escape sequences.\n\n"
        "9. Always include defaults for missing fields (processing_conditions, characterisation, "
        "properties_of_composition).\n\n"
        "### Output Format\n"
        "Return your answer as valid JSON strictly matching this schema:\n"
        "{\n"
        "  \"compositions\": [\n"
        "    {\n"
        "      \"composition\": \"string (as written in paper, append [Direction] if applicable)\",\n"
        "      \"role\": \"string (Target or Reference)\",\n"
        "      \"composition_normalized\": \"string or null (pure chemical formula)\",\n"
        "      \"source_doi\": \"string or null (DOI of paper)\",\n"
        "      \"main_phase\": \"string or null (BCC/FCC/HCP/etc.)\",\n"
        "      \"has_precipitates\": \"boolean (true/false)\",\n"
        "      \"grain_size_avg_um\": \"float or null (in micrometers)\",\n"
        "      \"grain_size_text\": \"string or null (original text about grain size)\",\n"
        "      \"processing_conditions\": \"string or null\",\n"
        "      \"processing_params\": \"object or null (structured params with standard keys)\",\n"
        "      \"process_category\": \"string or null (AM_DED/LPBF/SLM/SPS/etc.)\",\n"
        "      \"build_orientation\": \"string or null (Parallel-BD/Perpendicular-BD/etc.)\",\n"
        "      \"xrd_details\": \"string or null (XRD instrument + phase ID only)\",\n"
        "      \"microstructure_description\": \"string or null (grain morphology from SEM/EBSD/TEM)\",\n"
        "      \"characterisation\": {\n"
        "        \"XRD\": \"string (phase identification)\",\n"
        "        \"Microstructure\": \"string (grain morphology)\",\n"
        "        \"EBSD\": \"string (texture/orientation)\"\n"
        "      },\n"
        "      \"properties_of_composition\": [\n"
        "        {\n"
        "          \"property_name\": \"string (full descriptive name)\",\n"
        "          \"property_symbol\": \"string or null (standard abbreviation)\",\n"
        "          \"value\": \"string or null (original from paper)\",\n"
        "          \"value_numeric\": \"float or null (ML-ready)\",\n"
        "          \"value_type\": \"string (exact|lower_bound|upper_bound|range|qualitative|missing)\",\n"
        "          \"unit\": \"string or null\",\n"
        "          \"measurement_condition\": \"string or null (MUST start with 'at XXX K' if temperature is known)\",\n"
        "          \"additional_information\": \"string or null\"\n"
        "        }\n"
        "      ]\n"
        "    }\n"
        "  ]\n"
        "}\n\n"
        "### PROPERTY NAME AND SYMBOL (IMPORTANT):\n"
        "For each property, extract BOTH the descriptive name AND the symbol:\n\n"
        "- 'property_name': Full descriptive name of the property. If the paper provides a clear name, use it. \n"
        "  If only a symbol is given, infer the standard name from context.\n\n"
        "- 'property_symbol': Standard symbol/abbreviation as used in the paper. Use null if no symbol is provided.\n\n"
        "EXAMPLES (diverse materials science subfields):\n\n"
        "Thermal properties:\n"
        "  Tg → {\"property_name\": \"glass transition temperature\", \"property_symbol\": \"Tg\"}\n"
        "  Tm → {\"property_name\": \"melting temperature\", \"property_symbol\": \"Tm\"}\n"
        "  Tc → {\"property_name\": \"Curie temperature\", \"property_symbol\": \"Tc\"}\n"
        "  κ → {\"property_name\": \"thermal conductivity\", \"property_symbol\": \"κ\"}\n\n"
        "Mechanical properties:\n"
        "  E → {\"property_name\": \"Young's modulus\", \"property_symbol\": \"E\"}\n"
        "  H → {\"property_name\": \"hardness\", \"property_symbol\": \"H\"}\n"
        "  σ_y → {\"property_name\": \"yield strength\", \"property_symbol\": \"σ_y\"}\n"
        "  K_IC → {\"property_name\": \"fracture toughness\", \"property_symbol\": \"K_IC\"}\n\n"
        "Electrical/Magnetic properties:\n"
        "  ρ → {\"property_name\": \"electrical resistivity\", \"property_symbol\": \"ρ\"}\n"
        "  ε_r → {\"property_name\": \"relative permittivity\", \"property_symbol\": \"ε_r\"}\n"
        "  μ_r → {\"property_name\": \"relative permeability\", \"property_symbol\": \"μ_r\"}\n"
        "  M_s → {\"property_name\": \"saturation magnetization\", \"property_symbol\": \"M_s\"}\n\n"
        "Optical/Electronic properties:\n"
        "  E_g → {\"property_name\": \"band gap\", \"property_symbol\": \"E_g\"}\n"
        "  n → {\"property_name\": \"refractive index\", \"property_symbol\": \"n\"}\n"
        "  α → {\"property_name\": \"absorption coefficient\", \"property_symbol\": \"α\"}\n\n"
        "Structural/Compositional:\n"
        "  a → {\"property_name\": \"lattice parameter\", \"property_symbol\": \"a\"}\n"
        "  d → {\"property_name\": \"grain size\", \"property_symbol\": \"d\"}\n"
        "  ΔS_mix → {\"property_name\": \"mixing entropy\", \"property_symbol\": \"ΔS_mix\"}\n\n"
        "No symbol provided:\n"
        "  'particle size' → {\"property_name\": \"particle size\", \"property_symbol\": null}\n"
        "  'surface roughness' → {\"property_name\": \"surface roughness\", \"property_symbol\": null}\n\n"
        "Only symbol provided (infer name):\n"
        "  'ZT = 1.8' → {\"property_name\": \"thermoelectric figure of merit\", \"property_symbol\": \"ZT\"}\n\n"
        "### ML-READY PROPERTY ENCODING (CRITICAL):\n"
        "Each property MUST include three key fields to support human review AND ML training:\n\n"
        "1. 'value' (string or null) - Original value from paper, preserving fidelity:\n"
        "   - Exact: '683.0' for measured values\n"
        "   - Inequality: '>50' or '<2000' (keep symbols!)\n"
        "   - Range: '12-30'\n"
        "   - Qualitative: 'no plasticity', 'brittle'\n"
        "   - Missing: null (when table shows '-' or not reported)\n\n"
        "2. 'value_numeric' (float or null) - ML-ready numeric for database:\n"
        "   - Exact: same as value → 683.0\n"
        "   - Inequality: boundary value → '>50' → 50.0, '<2000' → 2000.0\n"
        "   - Range: midpoint → '12-30' → 21.0\n"
        "   - Qualitative: mapped → 'no plasticity' → 0.0\n"
        "   - Missing: null\n\n"
        "3. 'value_type' (string) - Classification for processing:\n"
        "   - 'exact' : precise measurement\n"
        "   - 'lower_bound' : inequality with '>'\n"
        "   - 'upper_bound' : inequality with '<'\n"
        "   - 'range' : interval value\n"
        "   - 'qualitative' : textual descriptor\n"
        "   - 'missing' : not reported\n\n"
        "EXAMPLES:\n"
        "Exact: {\"property_name\":\"glass transition temperature\", \"property_symbol\":\"Tg\", \"value\":\"683.0\", \"value_numeric\":683.0, \"value_type\":\"exact\", \"unit\":\"K\"}\n"
        "Exact: {\"property_name\":\"Young's modulus\", \"property_symbol\":\"E\", \"value\":\"210\", \"value_numeric\":210.0, \"value_type\":\"exact\", \"unit\":\"GPa\"}\n"
        "Lower bound: {\"property_name\":\"critical casting diameter\", \"property_symbol\":\"Dc\", \"value\":\">50\", \"value_numeric\":50.0, \"value_type\":\"lower_bound\", \"unit\":\"mm\"}\n"
        "Upper bound: {\"property_name\":\"electrical resistivity\", \"property_symbol\":\"ρ\", \"value\":\"<10\", \"value_numeric\":10.0, \"value_type\":\"upper_bound\", \"unit\":\"μΩ·cm\"}\n"
        "Range: {\"property_name\":\"grain size\", \"property_symbol\":\"d\", \"value\":\"10-50\", \"value_numeric\":30.0, \"value_type\":\"range\", \"unit\":\"μm\"}\n"
        "Qualitative: {\"property_name\":\"fracture mode\", \"property_symbol\":null, \"value\":\"brittle\", \"value_numeric\":0.0, \"value_type\":\"qualitative\", \"unit\":null}\n"
        "Missing: {\"property_name\":\"thermal conductivity\", \"property_symbol\":\"κ\", \"value\":null, \"value_numeric\":null, \"value_type\":\"missing\", \"unit\":\"W/(m·K)\"}\n\n"
        "### FORMATTING RULES:\n"
        "- In 'measurement_condition': Include ONLY experimental conditions (temperature, sample size, technique, atmosphere, etc.)"
        "- In 'additional_information': Include citations, figure references, table references, and additional context"
        "- DO NOT include citations like '[35]', 'Table 1', 'Figure 3' in the measurement_condition field"
        "- Example:"
            "CORRECT:"
            "'measurement_condition': 'DSC; Ø3 mm sample; heating rate 20 K/min'"
            "'additional_information': 'Figure 3; Table 1 entry No.3; reference [35]'"
  
        "INCORRECT:"
            "'measurement_condition': 'DSC; Ø3 mm sample; Figure 3; Table 1 [35]'"
        "\n\n"
        "### NEGATIVE EXAMPLES - DO NOT EXTRACT AS TARGET:\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "The following types of materials should be marked as role='Reference', NOT 'Target':\n\n"
        "- Compositions like 316L, Ti-6Al-4V, IN718, CoCrMo that are ONLY mentioned in the introduction\n"
        "  or a 'comparison with literature' table, with NO original test data from THIS paper.\n"
        "- If you see a table that lists published results from other research groups (with references),\n"
        "  mark those compositions as role='Reference'.\n"
        "- Materials mentioned only in phrases like 'compared to 316L reported in [35]' or\n"
        "  'previous work on Ti64 showed...' should be role='Reference'.\n\n"
        "Only mark as role='Target' if the paper provides:\n"
        "  - Processing details for how the material was made\n"
        "  - Original experimental measurements (mechanical, thermal, etc.)\n"
        "  - Microstructure characterization from THIS work\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "### CRITICAL - FOCUS ON THIS PAPER'S OWN MATERIALS:\n"
        "═══════════════════════════════════════════════════════════════════════════\n"
        "Only extract materials that are SYNTHESIZED, FABRICATED, or TESTED in THIS paper.\n"
        "Materials mentioned in the Introduction or Literature Review as references to\n"
        "prior work should be marked as role='Reference' or OMITTED entirely.\n\n"
        "The Introduction section often mentions many alloy compositions from other studies\n"
        "(e.g., 'HfNbTiZrTa was reported by [12]', 'MoNbTaW showed excellent properties [15]').\n"
        "These are NOT target materials of this paper - do NOT extract them as role='Target'.\n\n"
        "Focus your extraction on the Experimental, Results, and Discussion sections where\n"
        "the paper's own materials are described with original data.\n"
        "═══════════════════════════════════════════════════════════════════════════\n\n"
        "Do not include any additional commentary or explanation in your response."
    )


def generate_user_prompt(text: str) -> str:
    """Wrap the user message around the paper text.

    This helper simply surrounds the document text with a short instruction to
    perform the extraction.  It can be extended in the future to include
    allowed property lists or other context if desired.
    """
    return (
        "Here is some information from a materials science literature:\n"
        f"{text}\n\n"
        "Extract data from it following the instructions."
    )