"""
Node for performing data extraction from the paper text.

This node constructs a combined prompt consisting of a system prompt and a
user prompt and passes it to the ``extraction_extractor`` from
:mod:`knowmat.extractors`. The system prompt is generated by
:func:`knowmat.prompt_generator.generate_system_prompt` and can be modified by
the sub-field detection and evaluation agents via ``state['updated_prompt']``.

Primary path uses TrustCall tool extraction. A conservative raw-JSON fallback
is kept for providers with unstable tool-call compatibility.
"""

import json
import logging
import re
from pathlib import Path
from typing import Any, Dict

from knowmat.extractors import CompositionList, extraction_extractor, get_llm
from knowmat.prompt_generator import generate_system_prompt, generate_user_prompt
from knowmat.states import KnowMatState
from knowmat.app_config import settings

logger = logging.getLogger(__name__)


def _persist_paper_text(path_str: Any, paper_text: str) -> None:
    """Best-effort persistence of enriched paper text back to markdown."""
    if not path_str:
        return
    try:
        out_path = Path(str(path_str))
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(paper_text, encoding="utf-8")
    except OSError as exc:
        logger.warning("Could not persist enriched paper text to %s: %s", path_str, exc)


def _flatten_message_content(content: Any) -> str:
    """Best-effort conversion from chat content blocks into plain text."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict):
                parts.append(str(block.get("text") or block.get("content") or ""))
            else:
                parts.append(str(block))
        return "\n".join(part for part in parts if part).strip()
    return str(content or "")


def _extract_json_object_text(text: str) -> str:
    """Extract the first valid JSON object from free-form model output."""
    payload = str(text or "").strip()
    if payload.startswith("```"):
        payload = re.sub(r"^```(?:json)?\s*", "", payload)
        payload = re.sub(r"\s*```$", "", payload)
    try:
        json.loads(payload)
        return payload
    except Exception:
        pass

    decoder = json.JSONDecoder()
    for match in re.finditer(r"\{", payload):
        try:
            obj, _ = decoder.raw_decode(payload[match.start():])
        except Exception:
            continue
        if isinstance(obj, dict):
            return json.dumps(obj, ensure_ascii=False)
    raise ValueError("Could not locate a valid JSON object in fallback response.")


_COMPACT_FALLBACK_SYSTEM = (
    "You are a materials-science extraction engine. Extract database-ready "
    "structured data from the paper text into ONE JSON object.\n\n"
    "Output schema — use EXACTLY these lowercase field names (snake_case), "
    "no prose, no markdown fences:\n"
    "{\n"
    '  "Paper_Metadata": {"Paper_Title": "...", "DOI": "... or null"},\n'
    '  "Paper_Routing": {"base_material": "Metals|Ceramics_Inorganic|Polymers|Composites|Organic_Small_Molecules",\n'
    '                     "application": "Structural|Functional",\n'
    '                     "research_paradigm": "Experimental|Pure_Simulation|Hybrid"},\n'
    '  "compositions": [ {\n'
    '      "sample_id": "...", "role": "Target|Variant|Reference|Comparator",\n'
    '      "data_nature": "Experimental|Computed|Literature_Experimental|Literature_Computed",\n'
    '      "nominal_composition": {"<element_or_component>": "<value>"},\n'
    '      "processing_conditions": "free-text process summary",\n'
    '      "microstructure_description": "free-text microstructure summary",\n'
    '      "properties_of_composition": [ {\n'
    '          "property_name": "e.g. Yield_Strength",\n'
    '          "value_numeric": 0, "unit": "MPa",\n'
    '          "value_range": "null or e.g. 580-620",\n'
    '          "test_temperature_k": null,\n'
    '          "measurement_condition": "...",\n'
    '          "data_source": "text|table|image|image_digitized|unknown",\n'
    '          "note": "..." } ]\n'
    "  } ]\n"
    "}\n\n"
    "CRITICAL field names: the top-level list MUST be \"compositions\" (NOT \"items\"); "
    "the per-sample property list MUST be \"properties_of_composition\" (NOT \"Properties\"); "
    "each property uses \"property_name\"/\"value_numeric\"/\"unit\" (lowercase). "
    "Mismatched names are silently dropped — follow them exactly.\n"
    "EVERY sample with any measured/reported quantity MUST populate "
    "properties_of_composition — do not return an empty list when the paper "
    "reports strengths, hardness, elongation, densities, sizes, temperatures, etc. "
    "Extract ALL table rows and series points (one property record each).\n"
    "Split rules: each distinct composition / heat-treatment / aging time / "
    "thermal-exposure duration / parametric-sweep value / coating layer / "
    "computed (FEM/DFT/CALPHAD) case = a SEPARATE entry. Keep different test "
    "temperatures on the SAME unchanged specimen as ONE entry with multiple properties.\n"
    "Faithful to source: never invent values; ranges→value_range with value_numeric null; "
    "inequalities→value_numeric null + note; omit fields not mentioned.\n"
    "Figure blocks: '> [Figure N AI Description]' prose is CONTEXT ONLY (do not extract numbers). "
    "'> [Figure N VLM-digitized]' blocks ARE extractable — when you take a value from one, set "
    'data_source="image_digitized" and note="estimated from chart (VLM-digitized), not exact". '
    "Prefer text/table/caption values over digitized estimates for the same quantity."
)


def _invoke_plain_json_fallback(full_prompt: str, compact_user: str | None = None) -> Dict[str, Any]:
    """Fallback path for providers that fail structured tool calling.

    When *compact_user* is provided, use a much shorter system+user prompt
    (core schema + split/faithfulness rules only) instead of the full ~22k-token
    template.  Long papers frequently exhaust the model's generation budget
    under the full prompt and return only Paper_Metadata; the compact prompt
    leaves far more room to actually emit the compositions list.
    """
    llm = get_llm(agent_type="extraction")
    if compact_user is not None:
        messages = [
            {"role": "system", "content": _COMPACT_FALLBACK_SYSTEM},
            {"role": "user", "content": compact_user},
            {"role": "user", "content": "Return raw JSON only. Do not call any tool. "
                                        "Top-level list key MUST be \"compositions\"."},
        ]
        response = llm.invoke(messages)
    else:
        fallback_prompt = (
            full_prompt
            + "\n\nIMPORTANT: Do not call any tool."
            + "\nReturn raw JSON only."
            + "\nReturn exactly one JSON object with top-level key `compositions`."
        )
        response = llm.invoke(fallback_prompt)
    content = _flatten_message_content(getattr(response, "content", response))
    payload = _extract_json_object_text(content)
    model = CompositionList.model_validate_json(payload)
    return json.loads(model.model_dump_json())


def _count_extracted_props(extracted: Dict[str, Any]) -> int:
    """Total property records across all compositions/items in a result dict."""
    if not isinstance(extracted, dict):
        return 0
    comps = extracted.get("compositions") or extracted.get("items") or []
    total = 0
    for c in comps:
        if isinstance(c, dict):
            total += len(c.get("properties_of_composition") or c.get("Properties_Info") or [])
    return total


_PROP_SIGNAL_RE = re.compile(
    r"\d\s*(?:MPa|GPa|HV|HRC|kN|μm|um|nm|mm|wt\.?%|at\.?%|vol\.?%|°C|\bK\b|mAh|S/cm|%)",
    re.IGNORECASE,
)


def _paper_has_property_signals(paper_text: str) -> bool:
    """Heuristic: does the paper text contain numeric property-like signals?

    Used to decide whether a 0-property extraction is suspicious (paper clearly
    reports measurable quantities) vs legitimately empty.
    """
    if not paper_text:
        return False
    return len(_PROP_SIGNAL_RE.findall(paper_text)) >= 3


def _log_extraction_diag(path: str, extracted: Dict[str, Any]) -> None:
    """Log which extraction path produced the result and its property counts.

    Helps diagnose NO_PROPERTIES: shows whether the model emitted compositions
    with empty properties_of_composition (model issue) vs a downstream drop.
    """
    try:
        comps = extracted.get("compositions") or extracted.get("items") or []
        prop_counts = [
            len(c.get("properties_of_composition") or c.get("Properties_Info") or [])
            for c in comps
            if isinstance(c, dict)
        ]
        total = sum(prop_counts)
        msg = (
            f"[EXTRACT-DIAG] path={path} compositions={len(comps)} "
            f"total_props={total} per_comp={prop_counts}"
        )
        logger.warning(msg)
        print(f"   {msg}")
    except Exception as exc:
        logger.debug("extraction diag failed: %s", exc)


def extract_data(state: KnowMatState) -> Dict[str, Any]:
    """Perform the main LLM extraction and return the structured data."""
    import time as _time

    paper_text = state.get("paper_text", "")
    original_paper_text = paper_text
    paper_text_path = state.get("paper_text_path")
    routing_supplements = state.get("routing_supplements", "")
    paper_routing = state.get("paper_routing") or {}

    # Stage 2: inject multimodal figure descriptions into paper_text before extraction
    # Uses Approach C: CLIP alignment + VLM with context
    if settings.figure_description_enabled:
        ocr_items = state.get("ocr_items") or []
        if ocr_items:
            from knowmat.pdf.figure_describer import inject_figure_descriptions
            logger.info("Injecting figure descriptions (Approach C: VLM+CLIP)...")
            t0 = _time.time()
            try:
                _output_dir = state.get("output_dir") or ""
                if not _output_dir and paper_text_path:
                    _output_dir = str(Path(paper_text_path).parent.parent)
                _paper_id = ""
                if _output_dir:
                    _paper_id = Path(_output_dir).name
                paper_text = inject_figure_descriptions(
                    paper_text, ocr_items,
                    paper_id=_paper_id, output_dir=_output_dir,
                )
                elapsed = _time.time() - t0
                logger.info("✓ Figure descriptions injected in %.1fs.", elapsed)
                print(f"   Figure descriptions: {elapsed:.1f}s")
            except Exception as exc:
                logger.warning("Figure description injection failed: %s", exc, exc_info=True)

    if paper_text != original_paper_text:
        _persist_paper_text(paper_text_path, paper_text)

    system_prompt = generate_system_prompt(routing_supplements=routing_supplements)

    user_prompt = generate_user_prompt(
        paper_text,
        target_base_material=paper_routing.get("base_material", ""),
        target_application=paper_routing.get("application", ""),
        target_research_paradigm=paper_routing.get("research_paradigm", ""),
        target_patch_tags=", ".join(paper_routing.get("patch_tags", [])),
    )
    input_chars = len(system_prompt) + len(user_prompt)
    print(f"   Extraction input: ~{input_chars // 3} tokens")
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
        {"role": "user", "content": "Provide your response using the tool."},
    ]
    full_prompt = system_prompt + "\n\n" + user_prompt + "\n\n" + (
        "Provide your response using the tool."
    )

    structured_error: Exception | None = None
    t_extract = _time.time()
    try:
        result = extraction_extractor.invoke({"messages": messages})
    except Exception as exc:
        structured_error = exc
        _is_int_overflow = "integer exceeds 64-bit range" in str(exc).lower()
        if _is_int_overflow:
            logger.warning(
                "Structured extraction hit integer overflow; "
                "skipping structured retries, jumping to raw-JSON fallback. Error: %s",
                exc,
            )
            result = None
        else:
            logger.warning(
                "Structured extraction with role-separated messages failed; "
                "falling back to legacy prompt. Error: %s",
                exc,
            )
            try:
                result = extraction_extractor.invoke(full_prompt)
            except Exception as exc2:
                logger.warning("Legacy structured extraction also failed: %s", exc2)
                result = None

    responses = (result or {}).get("responses") or []
    if not responses and not (structured_error and "integer exceeds 64-bit range" in str(structured_error).lower()):
        print(f"   Extraction attempt 1: {_time.time() - t_extract:.1f}s (no responses, retrying)")
        try:
            fallback_result = extraction_extractor.invoke(full_prompt)
        except Exception as exc:
            if structured_error is None:
                structured_error = exc
            else:
                logger.warning("Structured fallback returned no responses: %s", exc)
            fallback_result = None
        responses = (fallback_result or {}).get("responses") or []
    extraction_elapsed = _time.time() - t_extract
    print(f"   Extraction LLM call: {extraction_elapsed:.1f}s")

    if not responses:
        logger.warning(
            "Tool-based extraction returned no structured responses; "
            "attempting raw-JSON fallback."
        )
        # Build a compact user message: routing hints + the (already
        # figure-enriched) paper text, WITHOUT the ~22k-token step-by-step
        # template.  This frees generation budget so long papers can actually
        # emit the compositions list instead of stopping after Paper_Metadata.
        _rt = paper_routing or {}
        compact_user = (
            "Routing hints (may be empty): "
            f"base_material={_rt.get('base_material','')}, "
            f"application={_rt.get('application','')}, "
            f"research_paradigm={_rt.get('research_paradigm','')}\n\n"
            "=== PAPER TEXT START ===\n"
            f"{paper_text}\n"
            "=== PAPER TEXT END ==="
        )
        try:
            extracted_dict = _invoke_plain_json_fallback(full_prompt, compact_user=compact_user)
            _log_extraction_diag("compact-fallback", extracted_dict)
            return {"latest_extracted_data": extracted_dict, "paper_text": paper_text}
        except Exception as compact_exc:
            logger.warning("Compact fallback failed (%s); trying full-prompt fallback.", compact_exc)
            try:
                extracted_dict = _invoke_plain_json_fallback(full_prompt)
                _log_extraction_diag("full-fallback", extracted_dict)
                return {"latest_extracted_data": extracted_dict, "paper_text": paper_text}
            except Exception as fallback_exc:
                if structured_error is not None:
                    raise RuntimeError(
                        "Extraction failed in both structured and raw-JSON modes: "
                        f"{structured_error}; fallback={fallback_exc}"
                    ) from fallback_exc
                raise

    response = responses[0]
    if isinstance(response, CompositionList):
        extracted_dict = json.loads(response.model_dump_json())
    else:
        extracted_dict = response

    # Quality gate: MiniMax tool-calling sometimes returns a syntactically valid
    # but content-empty result (e.g. 1 composition, 0 properties) which trustcall
    # accepts as a non-empty response — so the no-responses fallback above never
    # fires.  If the primary result has zero properties yet the paper clearly
    # reports measurable quantities, treat it as incomplete and run the compact
    # fallback (which reliably extracts properties on these papers).
    _primary_props = _count_extracted_props(extracted_dict)
    if _primary_props == 0 and _paper_has_property_signals(paper_text):
        logger.warning(
            "Primary extraction returned 0 properties but paper has property "
            "signals; retrying via compact fallback."
        )
        _rt = paper_routing or {}
        compact_user = (
            "Routing hints (may be empty): "
            f"base_material={_rt.get('base_material','')}, "
            f"application={_rt.get('application','')}, "
            f"research_paradigm={_rt.get('research_paradigm','')}\n\n"
            "=== PAPER TEXT START ===\n"
            f"{paper_text}\n"
            "=== PAPER TEXT END ==="
        )
        try:
            salvaged = _invoke_plain_json_fallback(full_prompt, compact_user=compact_user)
            if _count_extracted_props(salvaged) > 0:
                _log_extraction_diag("primary->compact-salvage", salvaged)
                return {"latest_extracted_data": salvaged, "paper_text": paper_text}
        except Exception as exc:
            logger.warning("Property-salvage compact fallback failed: %s", exc)

    _log_extraction_diag("tool-primary", extracted_dict)
    return {"latest_extracted_data": extracted_dict, "paper_text": paper_text}
